config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	
	attr_accessor :remember_token
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	# Returns the hash digest of the given string
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Remembers a user in the db for use in persistent sessions
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Remembers true if the given token matches the digest
	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	# Forgets a user
	def forget
		update_attribute(:remember_digest, nil)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_back_or user
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def new
  	@user = User.new
  end

  def create 
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      flash[:success] = "Welcome to the My Portfolio!"
      redirect_to @user
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy 
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

    # Before filters

    # Confirms a logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end

    # Confirms the correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis
	def full_title(page_title = '')
		base_title = 'My Portfolio'
		if page_title.empty?
			base_title
		else
			page_title + ' | ' + base_title
		end
	end
	
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in the particular user
	def log_in(user)
		session[:user_id] = user.id
	end

	# Remembers a user in a persistent session
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	# Returns true if the given user is the current user
	def current_user?(user)
		user == current_user
	end

	# Returns the current logged-in user (if any)
	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	# Returns true if the user is logged in, otherwise false
	def logged_in?
		!current_user.nil?
	end

	# Forgets a persistent session
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end
	
	# Logs out the current user
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	# Redirects to stored location (or to the default)
	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	# Stores the URL trying to be accessed
	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the particular user
	def gravatar_for(user, options = { size: 80 } )
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/layouts/_about.html.erb
<section class="about alt-bg animatedEntrance" id="about">
  <div class="container">
    <div class="row">

      <!-- Main box -->
      <div class="col-xs-12 col-md-4">
        <div class="main-box">
          <h3>Kamil Oleksiuk</h3>
          <p>Web Developer</p>
        </div>
      </div>

      <!-- Personal details box -->
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="box">
          <span class="icon" id="personal-details-icon"></span>
          <div class="scrollable-content">
            <h4 class="about-section-title">Personal Details</h4>
            <ul class="about-section-list personal-details">
              <li>
                <span class="personal-details-title">Nationality</span>
                <p>Polish</p>
              </li>
              <li>
                <span class="personal-details-title">Location</span>
                <p>Warsaw</p>
              </li>
              <li>
                <span class="personal-details-title">Age</span>
                <p>27</p>
              </li>
              <li>
                <span>Availability</span>
                <p>Full-time</p>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Education box -->
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="box">
          <span class="icon education-icon"></span>
          <div class="scrollable-content">
            <h4 class="about-section-title">Education</h4>
            <ul class="about-section-list education-list">
              <li class="col-sm-6 col-md-12">
                <span class="education-title">Medical University of Warsaw<br>Oct 2009 - Jul 2014</span>
                <p class="education-paragraph">Clinical Laboratory Science<br>study type: Master</p>
              </li>
              <li class="col-sm-6 col-md-12">
                <span class="education-title">Front-end course<br>Jan 2016 - Jun 2016</span>
                <p class="education-paragraph">Organised by Coders Lab</p>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">

      <!-- Work box -->
      <div class="col-xs-12 col-md-4">
        <div class="box">
          <span class="icon work-icon"></span>
          <div class="scrollable-content">
            <h4 class="about-section-title">Work</h4>
            <ul class="about-section-list">
              <li>
                <span class="work-title">Software Tester<br>Nov 2014 - now</span>
                <ul class="work-details-list">
                  <li>
                    <i class="fa fa-hand-o-right" aria-hidden="true"></i>
                    Manual testing mobile applications for: iOS, Android, Windows Phone
                  </li>
                  <li>
                    <i class="fa fa-cogs" aria-hidden="true"></i>
                    Manual and automated testing web applications using Selenium + Ruby
                  </li>
                  <li>
                    <i class="fa fa-list-alt" aria-hidden="true"></i>
                    Preparing software test plans, test strategies, test scenarios, development and execution of test cases based on use cases and requirement documents
                  </li>
                </ul>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>

      <!-- First skills box -->
      <div class="col-xs-12 col-md-4">
        <div class="box">
          <span class="icon skills-icon"></span>
          <div class="scrollable-content">
            <h4 class="about-section-title">Quality Assurance</h4>
            <ul class="about-section-list skills-list">
              <li>
                <span>Software testing</span>
                <div class="progress">
                  <div class="progress-bar-value">95%</div>
                  <div class="progress-bar" id="progress-software" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>Mobile/Web apps testing</span>
                <div class="progress">
                  <div class="progress-bar-value">95%</div>
                  <div class="progress-bar" id="progress-mobile" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>Test automation</span>
                <div class="progress">
                  <div class="progress-bar-value">60%</div>
                  <div class="progress-bar" id="progress-automation" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>Selenium</span>
                <div class="progress">
                  <div class="progress-bar-value">60%</div>
                  <div class="progress-bar" id="progress-selenium" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>Cucumber</span>
                <div class="progress">
                  <div class="progress-bar-value">60%</div>
                  <div class="progress-bar" id="progress-cucumber" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>

      <!-- Second skills box -->
      <div class="col-xs-12 col-md-4">
        <div class="box">
          <span class="icon skills-icon"></span>
          <div class="scrollable-content">
            <h4 class="about-section-title">Web development</h4>
            <ul class="about-section-list skills-list">
              <li>
                <span>HTML/CSS</span>
                <div class="progress">
                  <div class="progress-bar-value">85%</div>
                  <div class="progress-bar" id="progress-html-css" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>Sass/Less</span>
                <div class="progress">
                  <div class="progress-bar-value">80%</div>
                  <div class="progress-bar" id="progress-sass-less" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>Javascript</span>
                <div class="progress">
                  <div class="progress-bar-value">70%</div>
                  <div class="progress-bar" id="progress-js" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>jQuery</span>
                <div class="progress">
                  <div class="progress-bar-value">70%</div>
                  <div class="progress-bar" id="progress-jquery" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>Ajax</span>
                <div class="progress">
                  <div class="progress-bar-value">50%</div>
                  <div class="progress-bar" id="progress-ajax" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>Gulp</span>
                <div class="progress">
                  <div class="progress-bar-value">80%</div>
                  <div class="progress-bar" id="progress-gulp" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>Webpack</span>
                <div class="progress">
                  <div class="progress-bar-value">90%</div>
                  <div class="progress-bar" id="progress-webpack" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
              <li>
                <span>PHP</span>
                <div class="progress">
                  <div class="progress-bar-value">40%</div>
                  <div class="progress-bar" id="progress-php" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>  
        </div>
      </div>

    </div>
  </div>
</section>

app/views/layouts/_contact_form.html.erb
<!-- Contact -->
<section class="contact">
  <div class="container no-padding">
    <div class="row">

      <!-- Contact form -->
      <div class="col-xs-12 col-sm-6">
        <div class="form-wrapper">
          <div class="contact-form">
            <!-- Form will be here -->
          </div>
        </div>
      </div>

      <!-- Map -->
      <div class="col-xs-12 col-sm-6">
        <div class="map-wrapper embed-responsive embed-responsive-4by3">
          <iframe class="embed-responsive-item" width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJsc9_0orMHkcRb8JbC7iLC8w&key=AIzaSyAgV5MEV6VQHGw-5n5MMTwe2UAYS4MBS5Y" allowfullscreen></iframe>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container-fluid copyright">
		<div class="row">
			<div class="col-xs-12 col-sm-10 col-sm-offset-1 copyright-content">
				<p>Copyright 2017 @ Kamil Oleksiuk</p>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header alt-bg header-short">
	<div class="header-content">
		<div class="container">
			<div class="row">
				<div class="col-xs-12">

					<!-- Logo -->
					<div class="logo-wrapper pull-left">
						<%= link_to root_path, class: "main-logo" do %>
							<%= image_tag "logo.png", alt: "Main logo" %>
						<% end %>
					</div>

					<!-- Main menu -->
					<nav class="nav-main pull-right" id="main-nav">
						<ul class="main-nav-list visible-sm visible-md visible-lg">
							<li><%= link_to "Home", root_path, class: "menu-link-active page-scroll" %></li>
							<li><%= link_to "About", "#", class: "page-scroll" %></li>
							<li><%= link_to "Portfolio", "#", class: "page-scroll" %></li>
							<li><%= link_to "Contact", "#", class: "page-scroll" %></li>
							<li><%= link_to "Sign up", signup_path, class: "page-scroll" %></li>
							<% if logged_in? %>
								<li><%= link_to "Users", users_path %></li>
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">
										Account 
										<span class="caret"></span>
									</a>
									<ul class="dropdown-menu" role="menu">
										<li><%= link_to "Profile", current_user %></li>
              			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
              			<li class="divider"></li>
              			<li>
              				<%= link_to "Log out", logout_path, method: "delete" %>
              			</li>
              		</ul>
								</li>
							<% else %>
								<li><%= link_to "Log in", login_path, class: "page-scroll" %></li>
							<% end %>
						</ul>
					</nav>

					<!-- Header clearfix -->
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
</header>

<!-- Header separator -->
<div class="top-separator"></div>
<div class=""></div>

app/views/layouts/_main.html.erb
<section class="about alt-bg animatedEntrance" id="about">
  <div class="container">
    <div class="row">

      <!-- Main box -->
      <div class="col-xs-12 col-md-4">
        <div class="main-box">
          <h3>Kamil Oleksiuk</h3>
          <p>Web Developer</p>
        </div>
      </div>

      <!-- Personal details box -->
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="box">
          <span class="icon" id="personal-details-icon"></span>
          <h4 class="about-section-title">Personal Details</h4>
          <ul class="about-section-list personal-details">
            <li>
              <span class="personal-details-title">Nationality</span>
              <p>Polish</p>
            </li>
            <li>
              <span class="personal-details-title">Location</span>
              <p>Warsaw</p>
            </li>
            <li>
              <span class="personal-details-title">Age</span>
              <p>27</p>
            </li>
            <li>
              <span>Availability</span>
              <p>Full-time</p>
            </li>
          </ul>
        </div>
      </div>

      <!-- Education box -->
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="box">
          <span class="icon education-icon"></span>
          <h4 class="about-section-title">Education</h4>
          <ul class="about-section-list education-list">
            <li class="col-sm-6 col-md-12">
              <span class="education-title">Medical University of Warsaw<br>Oct 2009 - Jul 2014</span>
              <p class="education-paragraph">Clinical Laboratory Science<br>study type: Master</p>
            </li>
            <li class="col-sm-6 col-md-12">
              <span class="education-title">Front-end course<br>Jan 2016 - Jun 2016</span>
              <p class="education-paragraph">Organised by Coders Lab</p>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>

    <div class="row">

      <!-- Work box -->
      <div class="col-xs-12 col-md-4">
        <div class="box">
          <span class="icon work-icon"></span>
          <h4 class="about-section-title">Work</h4>
          <ul class="about-section-list">
            <li>
              <span class="work-title">Software Tester<br>Nov 2014 - now</span>
              <ul class="work-details-list">
                <li>
                  <i class="fa fa-hand-o-right" aria-hidden="true"></i>
                  Manual testing mobile applications for: iOS, Android, Windows Phone
                </li>
                <li>
                  <i class="fa fa-cogs" aria-hidden="true"></i>
                  Manual and automated testing web applications using Selenium + Ruby
                </li>
                <li>
                  <i class="fa fa-list-alt" aria-hidden="true"></i>
                  Preparing software test plans, test strategies, test scenarios, development and execution of test cases based on use cases and requirement documents
                </li>
              </ul>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
      </div>

      <!-- First skills box -->
      <div class="col-xs-12 col-md-4">
        <div class="box">
          <span class="icon skills-icon"></span>
          <h4 class="about-section-title">Quality Assurance</h4>
          <ul class="about-section-list skills-list">
            <li>
              <span>Software testing</span>
              <div class="progress">
                <div class="progress-bar-value">95%</div>
                <div class="progress-bar" id="progress-software" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>Mobile/Web apps testing</span>
              <div class="progress">
                <div class="progress-bar-value">95%</div>
                <div class="progress-bar" id="progress-mobile" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>Test automation</span>
              <div class="progress">
                <div class="progress-bar-value">60%</div>
                <div class="progress-bar" id="progress-automation" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>Selenium</span>
              <div class="progress">
                <div class="progress-bar-value">60%</div>
                <div class="progress-bar" id="progress-selenium" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>Cucumber</span>
              <div class="progress">
                <div class="progress-bar-value">60%</div>
                <div class="progress-bar" id="progress-cucumber" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
      </div>

      <!-- Second skills box -->
      <div class="col-xs-12 col-md-4">
        <div class="box">
          <span class="icon skills-icon"></span>
          <h4 class="about-section-title">Web development</h4>
          <ul class="about-section-list skills-list">
            <li>
              <span>HTML/CSS</span>
              <div class="progress">
                <div class="progress-bar-value">85%</div>
                <div class="progress-bar" id="progress-html-css" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>Sass/Less</span>
              <div class="progress">
                <div class="progress-bar-value">80%</div>
                <div class="progress-bar" id="progress-sass-less" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>Javascript</span>
              <div class="progress">
                <div class="progress-bar-value">70%</div>
                <div class="progress-bar" id="progress-js" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>jQuery</span>
              <div class="progress">
                <div class="progress-bar-value">70%</div>
                <div class="progress-bar" id="progress-jquery" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>Ajax</span>
              <div class="progress">
                <div class="progress-bar-value">50%</div>
                <div class="progress-bar" id="progress-ajax" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>Gulp</span>
              <div class="progress">
                <div class="progress-bar-value">80%</div>
                <div class="progress-bar" id="progress-gulp" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>Webpack</span>
              <div class="progress">
                <div class="progress-bar-value">90%</div>
                <div class="progress-bar" id="progress-webpack" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
            <li>
              <span>PHP</span>
              <div class="progress">
                <div class="progress-bar-value">40%</div>
                <div class="progress-bar" id="progress-php" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_slider.html.erb
<section class="top-slider hidden-xs" id="slider">
  <div id="top-slider" class="carousel slide" data-ride="carousel">

    <!-- Top slider content -->
    <div class="carousel-inner" role="listbox">

      <!-- First slider -->
      <div class="item active">
        <%= image_tag "slider_images/slider1.png", class: "slide-image" %>
        <div class="container">
          <div class="item-content">
            <h1>Hello, I am Kamil</h1>
            <h3>I am an awesome Web Developer who has creative visions, many ideas and can bring your concepts to life.</h3>
            <a class="btn btn-primary page-scroll" href="#">
              <i class="fa fa-chevron-down" href="#"></i>
              <span href="#about">See more</span>
            </a>
          </div>
        </div>
      </div>

      <!-- Second slider -->
      <div class="item">
        <%= image_tag "slider_images/slider2.png", class: "slide-image" %>
        <div class="container">
          <div class="item-content">
            <h1>Portfolio</h1>
            <h3>Check out my beautiful websites and get inspired.</h3>
            <a class="btn btn-primary page-scroll" href="#">
              <i class="fa fa-chevron-down" href="#"></i>
              <span href="#portfolio">See more</span>
            </a>
          </div>
        </div>
      </div>

    </div>

    <!-- Slider controls -->
    <a class="left carousel-control" href="#top-slider" role="button" data-slide="prev">
      <i class="fa fa-chevron-left"></i>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#top-slider" role="button" data-slide="next">
      <i class="fa fa-chevron-right"></i>
      <span class="sr-only">Next</span>
    </a>

    <!-- Carousel indicators -->
    <ol class="carousel-indicators">
      <li data-target="#top-slider" data-slide-to="0" class="active"></li>
      <li data-target="#top-slider" data-slide-to="1"></li>
    </ol>

  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  	<%= render 'layouts/header' %>
    <%= render 'layouts/slider' unless current_page?(signup_path) || current_page?(login_path)  %>

		<div id="main-content">

      <% unless current_page?(signup_path) || current_page?(login_path) %>

        <a href="https://github.com/koleksiuk20">
          <img class="gh-fork" src="https://camo.githubusercontent.com/52760788cde945287fbb584134c4cbc2bc36f904/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f77686974655f6666666666662e706e67" alt="Fork me on Github" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_white_ffffff.png">
        </a>

        <%= render 'layouts/about' %>
        <%= render 'layouts/portfolio' %>
        <%= render 'layouts/socialmedia' %>
        <%= render 'layouts/contact_form' %>

      <% end %>

      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "flash-alert alert alert-#{message_type}") %>
      <% end %>

			<%= yield %>

      <!-- Footer -->
      <%= render 'layouts/footer' %>
		</div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<section class="home-sign-up">
  <div class="container">
    <div class="row">
    	<header class="section-title">
				<h2>Join me today - it only takes a few seconds</h2>
				<div class="section-line">
          <span class="section-line-span"><i class="fa fa-sun-o"></i></span>
        </div>
      </header>
      <div class="sign-up-button">
      	<%= link_to "Sign up now!", signup_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</section>